# Assignment 1: Numpy

Perform the follwing tasks:


In [23]:
#3.1: import the numpy library
import numpy as np

In [24]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.55035099, 0.70201496, 0.79624998, 0.69618457, 0.99079543,
        0.33842589, 0.88100139, 0.83628822, 0.49282676, 0.50361817],
       [0.56186423, 0.16267392, 0.1930869 , 0.3515878 , 0.80525464,
        0.69078204, 0.86835376, 0.84578396, 0.55118809, 0.77686987],
       [0.76672488, 0.44604694, 0.59647657, 0.72090723, 0.94973275,
        0.11662575, 0.4730085 , 0.61148607, 0.15291565, 0.62383657],
       [0.60787574, 0.53145348, 0.17695065, 0.20090521, 0.2087258 ,
        0.6968033 , 0.0773585 , 0.38754129, 0.08990656, 0.59541019],
       [0.75929643, 0.94377496, 0.86735007, 0.91659878, 0.02334622,
        0.38304245, 0.49847073, 0.88828579, 0.54626606, 0.1237689 ],
       [0.12463516, 0.95746117, 0.86474442, 0.27160253, 0.81417336,
        0.21751297, 0.58414467, 0.03208897, 0.34297242, 0.60984008],
       [0.67323104, 0.88805401, 0.45908071, 0.41942544, 0.34508768,
        0.69619121, 0.91377181, 0.50191223, 0.16739155, 0.48430746],
       [0.92516548, 0.66720421, 0.6204339

In [25]:
#3.3: return only the odd rows of A
A[0:10:2] #lower:upper:step

array([[0.55035099, 0.70201496, 0.79624998, 0.69618457, 0.99079543,
        0.33842589, 0.88100139, 0.83628822, 0.49282676, 0.50361817],
       [0.76672488, 0.44604694, 0.59647657, 0.72090723, 0.94973275,
        0.11662575, 0.4730085 , 0.61148607, 0.15291565, 0.62383657],
       [0.75929643, 0.94377496, 0.86735007, 0.91659878, 0.02334622,
        0.38304245, 0.49847073, 0.88828579, 0.54626606, 0.1237689 ],
       [0.67323104, 0.88805401, 0.45908071, 0.41942544, 0.34508768,
        0.69619121, 0.91377181, 0.50191223, 0.16739155, 0.48430746],
       [0.07096893, 0.75338802, 0.92337346, 0.56460137, 0.52170682,
        0.18737117, 0.0183058 , 0.91415836, 0.60773402, 0.71173253]])

In [26]:
#3.4: perform a matrix multiplication of A with it's transposed

np.dot(A, A.T)  # .T um die Matrix A zu tranponieren



array([[4.98265677, 3.9887847 , 4.01002451, 2.16743512, 4.07549903,
        3.51629505, 3.78018012, 4.85437701, 3.71514266, 3.41957692],
       [3.9887847 , 4.00538947, 3.21417811, 2.08927896, 2.93468093,
        2.49130914, 3.20412945, 4.05747313, 2.76574494, 3.39501824],
       [4.01002451, 3.21417811, 3.58811783, 1.89176062, 3.18782083,
        2.76166198, 2.96428905, 4.09042248, 2.97018099, 2.74432157],
       [2.16743512, 2.08927896, 1.89176062, 1.77150052, 2.07815073,
        1.56525977, 2.17244756, 2.3509129 , 1.79391068, 2.23389048],
       [4.07549903, 2.93468093, 3.18782083, 2.07815073, 4.55820832,
        2.68209078, 3.4593734 , 4.01829009, 3.40850076, 2.89279648],
       [3.51629505, 2.49130914, 2.76166198, 1.56525977, 2.68209078,
        3.29579651, 2.78012337, 3.5915666 , 2.83003633, 2.35663366],
       [3.78018012, 3.20412945, 2.96428905, 2.17244756, 3.4593734 ,
        2.78012337, 3.58178893, 3.71876232, 2.61000113, 2.96870027],
       [4.85437701, 4.05747313, 4.0904224

In [27]:
#3.5: compute the matrix inverse of A
A_inv=np.linalg.inv(A)
A_inv

array([[-3.77323389e+00,  2.37376961e+00,  2.67751258e+00,
        -6.45536153e-01,  3.32077193e+00,  3.11030537e+00,
        -2.93070521e+00, -1.66305985e+00, -2.41788121e+00,
         1.23080245e+00],
       [ 3.74544457e+00, -3.91342984e+00, -1.78693843e+00,
         3.85067597e-01, -3.05694500e+00, -3.08314330e+00,
         3.35850993e+00,  1.57660172e+00,  1.68052253e+00,
         2.01160119e-01],
       [-6.09719349e+00,  5.26085867e+00,  3.10095912e+00,
        -7.68504443e-01,  5.59601256e+00,  6.28377931e+00,
        -5.42613723e+00, -3.28540022e+00, -2.89757720e+00,
         5.10558908e-01],
       [ 5.14314808e+00, -3.91878507e+00, -2.93295632e+00,
         1.58673548e+00, -4.31250749e+00, -5.31096633e+00,
         4.19403151e+00,  3.31347318e+00,  2.88395828e+00,
        -2.15813273e+00],
       [ 4.18953123e+00, -1.87208202e+00, -1.34859594e+00,
         1.67264103e+00, -1.74602410e+00, -1.28023728e+00,
        -3.58634966e-01,  6.58401973e-01, -8.09232702e-02,
        -1.

In [34]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask=A>0.5
mask
A[mask]/=2
A

array([[0.27517549, 0.35100748, 0.39812499, 0.34809228, 0.49539771,
        0.33842589, 0.44050069, 0.41814411, 0.49282676, 0.25180908],
       [0.28093211, 0.16267392, 0.1930869 , 0.3515878 , 0.40262732,
        0.34539102, 0.43417688, 0.42289198, 0.27559404, 0.38843493],
       [0.38336244, 0.44604694, 0.29823829, 0.36045361, 0.47486637,
        0.11662575, 0.4730085 , 0.30574303, 0.15291565, 0.31191829],
       [0.30393787, 0.26572674, 0.17695065, 0.20090521, 0.2087258 ,
        0.34840165, 0.0773585 , 0.38754129, 0.08990656, 0.29770509],
       [0.37964822, 0.47188748, 0.43367503, 0.45829939, 0.02334622,
        0.38304245, 0.49847073, 0.44414289, 0.27313303, 0.1237689 ],
       [0.12463516, 0.47873059, 0.43237221, 0.27160253, 0.40708668,
        0.21751297, 0.29207233, 0.03208897, 0.34297242, 0.30492004],
       [0.33661552, 0.44402701, 0.45908071, 0.41942544, 0.34508768,
        0.3480956 , 0.45688591, 0.25095612, 0.16739155, 0.48430746],
       [0.46258274, 0.3336021 , 0.3102169